name: Deploy Frontend ao GitHub Pages

on:
  push:
    branches:
      - Dev
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências
        working-directory: ./frontend
        run: |
          rm -rf node_modules
          npm install

      - name: Build do Angular
        working-directory: ./frontend
        run: |
          chmod +x ./node_modules/.bin/ng
          npm run build -- --base-href /Trab2-TW/

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist/webtech-final-project-frontend-template/browser